Repository jfrog/gofrog, pull requests merged in 2024-01, with the labels that each got.

#43 Replace archiver package with jfrog/archiver
  go.mod
  go.sum
  unarchive/archive.go
Labels: improvement

#44 Allow Stripping Components for Unarchiving
  unarchive/archive.go
  unarchive/archive_test.go
  unarchive/testdata/archives/strip-components.tar
  unarchive/testdata/archives/strip-components.tar.gz
  unarchive/testdata/archives/strip-components.zip
Labels: improvement

#45 Set - make set from slice & add slice to set
  datastructures/set.go
  datastructures/set_test.go
Labels: new feature

#48 Sets interactions
  .github/workflows/analysis.yml
  datastructures/set.go
  datastructures/set_test.go
  fanout/reader_test.go
  io/fileutils.go
  parallel/bounded_runner_test.go
Labels: new feature

#50 Added nil checks to sets union and intersect operations
  datastructures/set.go
Labels: ignore for release
